# Configuration for actions/labeler

frontend:
  - 'frontend/**/*'

backend:
  - 'backend/**/*'

python-ai-service:
  - 'python-ai-service/**/*'

documentation:
  - 'docs/**/*'
  - '*.md'
  - 'LICENSE'
  - 'SECURITY.md'

ci-cd:
  - '.github/workflows/**/*'
